### ISSUE TITLE
Missing CFG_python

### ISSUE THREAD

**Issue by ANONYEXP** [IBM/tree-sitter-codeviews#3]
I would like to ask if CFG_java and DFG_java files can also be used to produce CFG and DFG for python source code?

**Comment by Alex-Mathai-98** [comment]
@debesheedas - could you elaborate on the above question ?

**Comment by debesheedas** [comment]
@ANONYEXP No, currently, the repository does not support generating CFG and DFG for python source code. In future updates, when CFG_python and DFG_python are added, it will be able to support CFG and DFG for python source code.

**Comment by ANONYEXP** [comment]
Thanks for your reply. Actually, I'm quite looking forward to CFG_python and DFG_python files.
